FROM ubuntu:23.04

RUN apt update && apt upgrade -y

RUN apt install -y git wget make clang build-essential zlib1g-dev cmake gcc libssl-dev iputils-ping findutils hostname

WORKDIR /app

RUN git clone https://github.com/Miftahul7838/my_web_server.git

WORKDIR /app/my_web_server/python_source_code/Python-3.12.0/
RUN chmod 777 configure
RUN ./configure
WORKDIR /app/my_web_server/python_source_code/Python-3.12.0/
RUN make
WORKDIR /app/my_web_server/python_source_code/Python-3.12.0/
RUN make install
RUN python3.12 --version
WORKDIR /app/my_web_server/Code/bin/

CMD ["./webserver", "172.16.1.2", "80"]


