FROM ubuntu:23.04

RUN apt update && apt upgrade -y

RUN apt install -y git wget make clang build-essential zlib1g-dev cmake gcc libssl-dev iputils-ping findutils hostname python3

WORKDIR /app

RUN git clone https://github.com/Miftahul7838/my_web_server.git

WORKDIR /app/my_web_server/Code/bin/

CMD ["python3", "./webserver", "172.16.1.2", "80"]


